const data = [
  { answer: "KERNEL", question: "What is the core component of an OS?" },
  { answer: "PROCESS", question: "What is a running instance of a program?" },
  { answer: "THREAD", question: "What is the smallest unit of execution?" },
  { answer: "DEADLOCK", question: "What is when processes wait forever for resources?" },
  { answer: "PAGING", question: "Which memory scheme avoids external fragmentation?" },
  { answer: "MUTEX", question: "Which lock allows only one thread at a time?" },
  { answer: "SEMAPHORE", question: "Which mechanism controls access by multiple processes?" },
  { answer: "THRASH", question: "What is when CPU spends more time swapping?" },
  { answer: "SWAP", question: "What is moving processes in and out of memory?" },
  { answer: "ZOMBIE", question: "Which process finished but still in table?" },
  { answer: "FORK", question: "Which system call creates a new process?" },
  { answer: "EXEC", question: "Which call replaces the current process image?" },
  { answer: "SHELL", question: "What is the OS command-line interface?" },
  { answer: "CACHE", question: "Which small fast memory lies between CPU and RAM?" },
  { answer: "LOADER", question: "Which component loads programs into memory?" },
  { answer: "VIRTUAL", question: "Which memory allows execution beyond RAM?" },
  { answer: "USER", question: "In which mode do applications run?" },
  { answer: "BOOT", question: "What is the OS startup process called?" },
  { answer: "TIME", question: "Round Robin scheduling is best for what?" },
  { answer: "FIFO", question: "Which algorithm removes the oldest page?" },
  { answer: "CLASS", question: "Which OOP unit groups fields and methods?" },
  { answer: "GET", question: "Which HTTP method fetches data?" },
  { answer: "POST", question: "Which HTTP method sends data to server?" },
  { answer: "PUT", question: "Which HTTP method updates a resource?" },
  { answer: "HEAP", question: "Which structure implements priority queues?" },
  { answer: "STACK", question: "Which structure follows LIFO?" },
  { answer: "QUEUE", question: "Which structure follows FIFO?" },
  { answer: "TREE", question: "Which structure is hierarchical?" },
  { answer: "GRAPH", question: "Which structure has nodes and edges?" },
  { answer: "NAN", question: "What is 0 divided by 0 in JavaScript?" },
  { answer: "CSS", question: "Which tech styles HTML?" },
  { answer: "HTML", question: "Which markup structures web pages?" },
  { answer: "JS", question: "Which language powers interactivity in browsers?" },
  { answer: "AJAX", question: "Which tech updates pages asynchronously?" },
  { answer: "REST", question: "Which style uses stateless APIs?" },
  { answer: "JSON", question: "Which format stores lightweight structured data?" },
  { answer: "XML", question: "Which markup is both human and machine readable?" },
  { answer: "OOP", question: "Which paradigm uses objects and classes?" },
  { answer: "ENCAP", question: "Which OOP concept hides details?" },
  { answer: "INHERIT", question: "Which OOP concept reuses parent class?" },
  { answer: "POLY", question: "Which OOP concept allows many forms?" },
  { answer: "ABSTR", question: "Which OOP concept shows only essentials?" },
  { answer: "NPM", question: "Which manager handles Node.js packages?" },
  { answer: "YARN", question: "Which alternative to npm exists?" },
  { answer: "TCP", question: "Which protocol ensures reliable delivery?" },
  { answer: "UDP", question: "Which protocol is faster but unreliable?" },
  { answer: "IP", question: "Which protocol addresses packets on network?" },
  { answer: "DNS", question: "Which service resolves names to IP?" },
  { answer: "SMTP", question: "Which protocol sends emails?" },
  { answer: "IMAP", question: "Which protocol reads emails from server?" },
  { answer: "FTP", question: "Which protocol transfers files?" },
  { answer: "SSH", question: "Which protocol securely logs into remote?" },
  { answer: "HTTP", question: "Which protocol serves the web?" },
  { answer: "HTTPS", question: "Which protocol is secure HTTP?" },
  { answer: "DIV", question: "Which HTML tag is a container?" },
  { answer: "SPAN", question: "Which HTML tag is inline container?" },
  { answer: "H1", question: "Which HTML tag defines main heading?" },
  { answer: "P", question: "Which HTML tag defines paragraph?" },
  { answer: "UL", question: "Which tag defines unordered list?" },
  { answer: "OL", question: "Which tag defines ordered list?" },
  { answer: "LI", question: "Which tag defines list item?" },
  { answer: "A", question: "Which tag creates hyperlink?" },
  { answer: "IMG", question: "Which tag displays image?" },
  { answer: "FORM", question: "Which tag defines form?" },
  { answer: "SQL", question: "Which language queries databases?" },
  { answer: "JOIN", question: "Which SQL clause combines tables?" },
  { answer: "CRUD", question: "Which acronym means Create Read Update Delete?" },
  { answer: "PK", question: "Which key uniquely identifies a record?" },
  { answer: "FK", question: "Which key links to another table?" },
  { answer: "VIEW", question: "Which SQL object is a saved query?" },
  { answer: "NULL", question: "Which value means no data?" },
  { answer: "C++", question: "Which language supports OOP and low-level?" },
  { answer: "JAVA", question: "Which language runs on JVM?" },
  { answer: "C", question: "Which language is procedural and low-level?" },
  { answer: "GO", question: "Which language by Google supports concurrency?" },
  { answer: "RUST", question: "Which language ensures memory safety?" },
  { answer: "PHP", question: "Which language powers WordPress?" },
  { answer: "PERL", question: "Which scripting language is known for regex?" },
  { answer: "RUBY", question: "Which language powers Rails?" },
  { answer: "SWIFT", question: "Which language builds iOS apps?" },
  { answer: "KOTLIN", question: "Which language is official for Android?" },
  { answer: "SCALA", question: "Which JVM language mixes OOP and FP?" },
  { answer: "R", question: "Which language is used for statistics?" },
  { answer: "MATLAB", question: "Which language is for math modeling?" },
  { answer: "MONGODB", question: "Which NoSQL database stores JSON docs?" },
  { answer: "MYSQL", question: "Which RDBMS is most common?" },
  { answer: "REDIS", question: "Which store is key-value in memory?" },
  { answer: "NEO4J", question: "Which DB specializes in graphs?" },
  { answer: "KAFKA", question: "Which tool is used for event streaming?" },
  { answer: "DOCKER", question: "Which tool containers applications?" },
  { answer: "GIT", question: "Which VCS tracks code changes?" },
  { answer: "HUB", question: "Which service hosts Git repos?" },
  { answer: "CI", question: "Which practice means continuous integration?" },
  { answer: "CD", question: "Which practice means continuous delivery?" },
  { answer: "API", question: "Which interface lets apps talk?" },
  { answer: "SDK", question: "Which kit provides tools for devs?" },
  { answer: "IDE", question: "Which tool combines editor, build, debug?" },
  { answer: "JVM", question: "Which machine runs Java bytecode?" },
  { answer: "RAM", question: "Which memory is volatile?" },
  { answer: "ROM", question: "Which memory is non-volatile?" },
  { answer: "SSD", question: "Which storage is faster than HDD?" },
  { answer: "BIOS", question: "Which firmware starts PC?" },
  { answer: "BUS", question: "Which connects components inside computer?" },
];

export default data;