// const data = [
//   { answer: "KERNEL", question: "What is the core component of an OS?" },
//   { answer: "PROCESS", question: "What is a running instance of a program?" },
//   { answer: "THREAD", question: "What is the smallest unit of execution?" },
//   { answer: "DEADLOCK", question: "What is when processes wait forever for resources?" },
//   { answer: "PAGING", question: "Which memory scheme avoids external fragmentation?" },
//   { answer: "MUTEX", question: "Which lock allows only one thread at a time?" },
//   { answer: "SEMAPHORE", question: "Which mechanism controls access by multiple processes?" },
//   { answer: "THRASH", question: "What is when CPU spends more time swapping?" },
//   { answer: "SWAP", question: "What is moving processes in and out of memory?" },
//   { answer: "ZOMBIE", question: "Which process finished but still in table?" },
//   { answer: "FORK", question: "Which system call creates a new process?" },
//   { answer: "EXEC", question: "Which call replaces the current process image?" },
//   { answer: "SHELL", question: "What is the OS command-line interface?" },
//   { answer: "CACHE", question: "Which small fast memory lies between CPU and RAM?" },
//   { answer: "LOADER", question: "Which component loads programs into memory?" },
//   { answer: "VIRTUAL", question: "Which memory allows execution beyond RAM?" },
//   { answer: "USER", question: "In which mode do applications run?" },
//   { answer: "BOOT", question: "What is the OS startup process called?" },
//   { answer: "TIME", question: "Round Robin scheduling is best for what?" },
//   { answer: "FIFO", question: "Which algorithm removes the oldest page?" },
//   { answer: "CLASS", question: "Which OOP unit groups fields and methods?" },
//   { answer: "GET", question: "Which HTTP method fetches data?" },
//   { answer: "POST", question: "Which HTTP method sends data to server?" },
//   { answer: "PUT", question: "Which HTTP method updates a resource?" },
//   { answer: "HEAP", question: "Which structure implements priority queues?" },
//   { answer: "STACK", question: "Which structure follows LIFO?" },
//   { answer: "QUEUE", question: "Which structure follows FIFO?" },
//   { answer: "TREE", question: "Which structure is hierarchical?" },
//   { answer: "GRAPH", question: "Which structure has nodes and edges?" },
//   { answer: "NAN", question: "What is 0 divided by 0 in JavaScript?" },
//   { answer: "CSS", question: "Which tech styles HTML?" },
//   { answer: "HTML", question: "Which markup structures web pages?" },
//   { answer: "JS", question: "Which language powers interactivity in browsers?" },
//   { answer: "AJAX", question: "Which tech updates pages asynchronously?" },
//   { answer: "REST", question: "Which style uses stateless APIs?" },
//   { answer: "JSON", question: "Which format stores lightweight structured data?" },
//   { answer: "XML", question: "Which markup is both human and machine readable?" },
//   { answer: "OOP", question: "Which paradigm uses objects and classes?" },
//   { answer: "ENCAP", question: "Which OOP concept hides details?" },
//   { answer: "INHERIT", question: "Which OOP concept reuses parent class?" },
//   { answer: "POLY", question: "Which OOP concept allows many forms?" },
//   { answer: "ABSTR", question: "Which OOP concept shows only essentials?" },
//   { answer: "NPM", question: "Which manager handles Node.js packages?" },
//   { answer: "YARN", question: "Which alternative to npm exists?" },
//   { answer: "TCP", question: "Which protocol ensures reliable delivery?" },
//   { answer: "UDP", question: "Which protocol is faster but unreliable?" },
//   { answer: "IP", question: "Which protocol addresses packets on network?" },
//   { answer: "DNS", question: "Which service resolves names to IP?" },
//   { answer: "SMTP", question: "Which protocol sends emails?" },
//   { answer: "IMAP", question: "Which protocol reads emails from server?" },
//   { answer: "FTP", question: "Which protocol transfers files?" },
//   { answer: "SSH", question: "Which protocol securely logs into remote?" },
//   { answer: "HTTP", question: "Which protocol serves the web?" },
//   { answer: "HTTPS", question: "Which protocol is secure HTTP?" },
//   { answer: "DIV", question: "Which HTML tag is a container?" },
//   { answer: "SPAN", question: "Which HTML tag is inline container?" },
//   { answer: "H1", question: "Which HTML tag defines main heading?" },
//   { answer: "P", question: "Which HTML tag defines paragraph?" },
//   { answer: "UL", question: "Which tag defines unordered list?" },
//   { answer: "OL", question: "Which tag defines ordered list?" },
//   { answer: "LI", question: "Which tag defines list item?" },
//   { answer: "A", question: "Which tag creates hyperlink?" },
//   { answer: "IMG", question: "Which tag displays image?" },
//   { answer: "FORM", question: "Which tag defines form?" },
//   { answer: "SQL", question: "Which language queries databases?" },
//   { answer: "JOIN", question: "Which SQL clause combines tables?" },
//   { answer: "CRUD", question: "Which acronym means Create Read Update Delete?" },
//   { answer: "PK", question: "Which key uniquely identifies a record?" },
//   { answer: "FK", question: "Which key links to another table?" },
//   { answer: "VIEW", question: "Which SQL object is a saved query?" },
//   { answer: "NULL", question: "Which value means no data?" },
//   { answer: "C++", question: "Which language supports OOP and low-level?" },
//   { answer: "JAVA", question: "Which language runs on JVM?" },
//   { answer: "C", question: "Which language is procedural and low-level?" },
//   { answer: "GO", question: "Which language by Google supports concurrency?" },
//   { answer: "RUST", question: "Which language ensures memory safety?" },
//   { answer: "PHP", question: "Which language powers WordPress?" },
//   { answer: "PERL", question: "Which scripting language is known for regex?" },
//   { answer: "RUBY", question: "Which language powers Rails?" },
//   { answer: "SWIFT", question: "Which language builds iOS apps?" },
//   { answer: "KOTLIN", question: "Which language is official for Android?" },
//   { answer: "SCALA", question: "Which JVM language mixes OOP and FP?" },
//   { answer: "R", question: "Which language is used for statistics?" },
//   { answer: "MATLAB", question: "Which language is for math modeling?" },
//   { answer: "MONGODB", question: "Which NoSQL database stores JSON docs?" },
//   { answer: "MYSQL", question: "Which RDBMS is most common?" },
//   { answer: "REDIS", question: "Which store is key-value in memory?" },
//   { answer: "NEO4J", question: "Which DB specializes in graphs?" },
//   { answer: "KAFKA", question: "Which tool is used for event streaming?" },
//   { answer: "DOCKER", question: "Which tool containers applications?" },
//   { answer: "GIT", question: "Which VCS tracks code changes?" },
//   { answer: "HUB", question: "Which service hosts Git repos?" },
//   { answer: "CI", question: "Which practice means continuous integration?" },
//   { answer: "CD", question: "Which practice means continuous delivery?" },
//   { answer: "API", question: "Which interface lets apps talk?" },
//   { answer: "SDK", question: "Which kit provides tools for devs?" },
//   { answer: "IDE", question: "Which tool combines editor, build, debug?" },
//   { answer: "JVM", question: "Which machine runs Java bytecode?" },
//   { answer: "RAM", question: "Which memory is volatile?" },
//   { answer: "ROM", question: "Which memory is non-volatile?" },
//   { answer: "SSD", question: "Which storage is faster than HDD?" },
//   { answer: "BIOS", question: "Which firmware starts PC?" },
//   { answer: "BUS", question: "Which connects components inside computer?" },
// ];



const data = [
  { answer: "వేలుపు", question: "మన దేశంలో పూజించేది?" },
  { answer: "కుమ్మరి", question: "మట్టితో కుండలు చేసేవారు?" },
  { answer: "ఆహారం", question: "మనం బ్రతకడానికి తినేది?" },
  { answer: "రైతు", question: "పొలంలో కష్టపడి పంట పండించేవాడు?" },
  { answer: "ఆట", question: "పిల్లలు సరదాగా ఆడేది?" },
  { answer: "నక్షత్రం", question: "రాత్రిపూట ఆకాశంలో మెరిసేది?" },
  { answer: "కవి", question: "కవితలు రాసేవాడు?" },
  { answer: "చేప", question: "నీటిలో ఉండే ప్రాణి?" },
  { answer: "పాలీ", question: "వడ్రంగి పనిలో వాడే పరికరం?" },
  { answer: "నిప్పు", question: "వేడిని ఇచ్చేది, వెలుగునిచ్చేది?" },
  { answer: "గాలి", question: "కంటికి కనిపించకుండా, మనం పీల్చేది?" },
  { answer: "వడ్రంగి", question: "చెక్కతో వస్తువులు చేసేవాడు?" },
  { answer: "పాము", question: "బుస్సున శబ్దం చేసే జంతువు?" },
  { answer: "జోల", question: "పిల్లల్ని నిద్రపుచ్చడానికి పాడే పాట?" },
  { answer: "పుస్తకం", question: "జ్ఞానాన్నిచ్చే వస్తువు?" },
  { answer: "అన్న", question: "మనల్ని పెంచి పెద్ద చేసినవారు?" },
  { answer: "తోడు", question: "మనం కష్టం వచ్చినప్పుడు ఆసరాగా నిలిచేది?" },
  { answer: "పలక", question: "బడిలో విద్యార్థులు వాడేది?" },
  { answer: "జైలు", question: "తప్పు చేసిన వారిని ఉంచే ప్రదేశం?" },
  { answer: "కూర్చు", question: "నిలుచున్నవాడు కూర్చుంటాడు" },
  
  { answer: "మామిడి", question: "పండ్ల రాజు?" },
  { answer: "గుడి", question: "దేవుడు ఉండే ప్రదేశం?" },
  { answer: "గ్రామం", question: "పల్లెటూరు?" },
  { answer: "కోతి", question: "చెట్ల మీద గెంతుతూ ఉండే జంతువు?" },
  { answer: "ఏనుగు", question: "జంతువులలో పెద్దది?" },
  { answer: "జోకు", question: "నవ్వించడానికి చెప్పేది?" },
  { answer: "జల", question: "నీటికి మరొక పేరు?" },
  { answer: "అడవి", question: "చాలా చెట్లు, జంతువులు ఉండే ప్రదేశం?" },
  { answer: "గీత", question: "ఒక పుస్తకం పేరు?" },
  { answer: "చేరు", question: "ఒక ప్రదేశం చేరుకోవడం?" },
  { answer: "గాయకుడు", question: "పాటలు పాడే వ్యక్తి?" },
  { answer: "నది", question: "నీరు ప్రవహించే మార్గం?" },
  { answer: "పూజారి", question: "గుడిలో పూజలు చేసే వ్యక్తి?" },
  { answer: "వేషం", question: "నటనలో వేసేది?" },
  { answer: "పాటశాల", question: "పిల్లలు చదువుకునే ప్రదేశం?" },
  { answer: "నేల", question: "మనం నడిచే ప్రదేశం?" },
  { answer: "పెళ్లి", question: "ఇద్దరు వ్యక్తులు కలిసే కార్యక్రమం?" },
  { answer: "నిద్ర", question: "మనం విశ్రాంతి తీసుకునే సమయం?" },
  { answer: "వేసవి", question: "చాలా వేడిగా ఉండే కాలం?" },
  { answer: "కవిత", question: "కవి రాసేది?" },
  { answer: "మంత్రం", question: "దేవుడిని ప్రార్థించేటప్పుడు చెప్పేది?" },
  { answer: "చెరసాల", question: "జైలుకు పర్యాయపదం?" },
  { answer: "పువ్వు", question: "చెట్టుకి ఉండేది, మంచి వాసనతో?" },
  { answer: "వేరు", question: "చెట్టు భూమిలో ఉండే భాగం?" },
  { answer: "శరీరం", question: "మనుషులకు ఉండేది?" },
  { answer: "రక్తం", question: "మన శరీరంలో ఎర్రగా ఉండేది?" },
  { answer: "చెప్పు", question: "మనం కాళ్లకు వేసుకునేది?" },
  { answer: "కలం", question: "రాసుకోవడానికి వాడేది?" },
  { answer: "మందు", question: "జబ్బు తగ్గుటకు వాడేది?" },
  { answer: "మంచం", question: "మనం పడుకునేది?" },
  { answer: "బండి", question: "వాహనానికి పర్యాయపదం?" },
  { answer: "కన్ను", question: "చూడడానికి ఉపయోగపడే అవయవం?" },
  { answer: "విల్లు", question: "రాముడు వాడినది?" },
  { answer: "కుంచె", question: "చిత్రాలు గీయడానికి వాడేది?" },
  { answer: "దారం", question: "గుడ్డలు కుట్టడానికి వాడేది?" },
  { answer: "సూది", question: "కుట్టడానికి వాడే పరికరం?" },
  { answer: "గది", question: "ఇంటిలో ఒక భాగం?" },
  { answer: "చీకటి", question: "వెలుగు లేని సమయం?" },
  { answer: "ఎలుగు", question: "అడవిలో ఉండే ఒక జంతువు?" },
  { answer: "కోకిల", question: "మధురంగా పాడే పక్షి?" },
  { answer: "కప్ప", question: "వర్షం పడినప్పుడు సంతోషించే ప్రాణి?" },
  { answer: "చేప", question: "నీటిలో బ్రతికేది?" },
  { answer: "పలుగు", question: "పనివారి చేతిలో ఉండేది?" },
  { answer: "పువ్వు", question: "దేవుడికి పూజ చేసేటప్పుడు వాడేది?" },
  { answer: "ధాన్యం", question: "పొలంలో పండించే పంట?" },
  { answer: "బస్తీ", question: "ఒక చిన్న పట్టణం?" },
  { answer: "అద్దం", question: "మన మొహం చూసుకునేది?" },
  { answer: "తాళం", question: "తలుపు మూయడానికి వాడేది?" },
  { answer: "పండు", question: "చెట్టు నుండి వచ్చే తీపి?" },
  { answer: "బంతి", question: "ఆటలకి ఉపయోగించేది?" },


];


const str= "బంతి";
let chars=Array.from(str);
console.log(chars);


// // function splitTeluguWord(str) {
// //   const segmenter = new Intl.Segmenter('te', { granularity: 'grapheme' });
// //   const graphemes = Array.from(segmenter.segment(str), s => s.segment);

// //   const result = [];
// //   for (const g of graphemes) {
// //     if (/[\u0C00-\u0C03]/.test(g) && result.length > 0) {
// //       const last = result.pop();
// //       result.push(last, g); 
// //     } else {
// //       result.push(g);
// //     }
// //   }
// //   return result;
// // }

// const str = "బంతి";
// console.log(splitTeluguWord(str));



export default data;